services:
  trakfinapi:
    image: ${DOCKER_REGISTRY-}trakfinapi
    build:
      context: ../TrakfinAPI
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    user: root
    container_name: sql_server2022
    volumes:
      - "./data-mssql:/var/opt/mssql/data"
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=y
  trakfinweb:
    image: ${DOCKER_REGISTRY-}trakfinweb
    build:
      context: ../Trakfin
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - trakfinapi
      - sql
