name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
    build:
      name: Push Docker Image to Docker Hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
  
        - name: Login to Docker Hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASSWORD}}
          run: |
            docker login -u $username -p $password

        - name: Build TrakfinAPI Docker Image
          run: |
            docker build -t trakfinapi ../TrakfinAPI

        - name: Tag and Push TrakfinAPI Docker Image to Docker Hub
          run: |
            docker tag trakfinapi ${{secrets.DOCKERHUB_USERNAME}}/trakfinapi:latest
            docker push ${{secrets.DOCKERHUB_USERNAME}}/trakfinapi:latest
