name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Build TrakfinAPI Docker Image
        run: |
          ls -la
          docker build -t trakfinapi ./TrakfinAPI

      - name: Tag and Push TrakfinAPI Docker Image to Docker Hub
        run: |
          docker tag trakfinapi ${{ secrets.DOCKERHUB_USERNAME }}/trakfinapi:${{ secrets.TRAKFINAPI_VERSION }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/trakfinapi:${{ secrets.TRAKFINAPI_VERSION }}

      - name: Build Trakfin Web Docker Image
        run: |
          ls -la
          docker build -t trakfinweb ./Trakfin

      - name: Tag and Push Trakfin Web Docker Image to Docker Hub
        run: |
          docker tag trakfinweb ${{ secrets.DOCKERHUB_USERNAME }}/trakfinweb:${{ secrets.TRAKFINWEB_VERSION }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/trakfinweb:${{ secrets.TRAKFINWEB_VERSION }}
